In [1]:
import pandas as pd
import numpy as np 

import seaborn as sns
import matplotlib.pyplot as plt

from pydataset import data
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import f_regression, SelectKBest, RFE 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


import warnings
warnings.filterwarnings('ignore')

## 1. Load the tips dataset.

 **a. Create a column named price_per_person. This should be the total bill divided by the party size.<br>**

In [2]:
tips = sns.load_dataset('tips')

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
tips['price_per_person'] = tips['total_bill']/tips['size']

tips.head()

   total_bill   tip     sex smoker  day    time  size  price_per_person
0       16.99  1.01  Female     No  Sun  Dinner     2          8.495000
1       10.34  1.66    Male     No  Sun  Dinner     3          3.446667
2       21.01  3.50    Male     No  Sun  Dinner     3          7.003333
3       23.68  3.31    Male     No  Sun  Dinner     2         11.840000
4       24.59  3.61  Female     No  Sun  Dinner     4          6.147500

### **b. Before using any of the methods discussed in the lesson, which features do you think would be most important for predicting the tip amount?<br>**

In [4]:
tips.corr()

                  total_bill       tip      size  price_per_person
total_bill          1.000000  0.675734  0.598315          0.647497
tip                 0.675734  1.000000  0.489299          0.347393
size                0.598315  0.489299  1.000000         -0.175412
price_per_person    0.647497  0.347393 -0.175412          1.000000

*I would say total_bill will be the most important for prediciting the tip amount*

In [5]:
train, val_test = train_test_split(tips, train_size=0.6, random_state=22)
    
val, test = train_test_split(val_test, train_size=0.5, random_state=22)

train.shape, val.shape, test.shape

((146, 8), (49, 8), (49, 8))

In [6]:
mms = MinMaxScaler()

train[['total_bill', 'size', 'price_per_person']] = mms.fit_transform(train[['total_bill', 'size', 'price_per_person']])

train.head()

     total_bill   tip     sex smoker  day    time  size  price_per_person
173    0.635882  3.18    Male    Yes  Sun  Dinner   0.2          0.961326
24     0.370084  3.18    Male     No  Sat  Dinner   0.2          0.518232
241    0.433053  2.00    Male    Yes  Sat  Dinner   0.2          0.623204
66     0.295625  2.47  Female     No  Sat  Dinner   0.2          0.394107
164    0.319046  3.00  Female    Yes  Sun  Dinner   0.2          0.433149

### **c. Use select k best to select the top 2 features for predicting tip amount. What are they?<br>**

In [7]:
X_train_scaled = train[['total_bill', 'size', 'price_per_person']]
y_train = train['tip']

In [8]:
f_selector = SelectKBest(f_regression, k = 2)

In [9]:
f_selector.fit(X_train_scaled, y_train)

SelectKBest(k=2, score_func=<function f_regression at 0x128ca0940>)

In [10]:
f_select_mask = f_selector.get_support()
f_select_mask

array([ True,  True, False])

In [11]:
X_train_scaled.columns[f_select_mask].tolist()

['total_bill', 'size']

In [12]:
X_train_scaled.iloc[:,f_select_mask]

     total_bill  size
173    0.635882   0.2
24     0.370084   0.2
241    0.433053   0.2
66     0.295625   0.2
164    0.319046   0.2
107    0.489174   0.2
91     0.429076   0.2
138    0.285683   0.2
1      0.160627   0.4
39     0.623067   0.4
123    0.284578   0.2
92     0.059213   0.2
22     0.280601   0.2
130    0.353734   0.2
191    0.369863   0.2
196    0.160627   0.2
67     0.000000   0.0
9      0.258727   0.2
209    0.214096   0.2
64     0.320813   0.4
242    0.325895   0.2
35     0.463765   0.4
230    0.462660   0.6
98     0.396376   0.2
97     0.197967   0.2
104    0.394388   0.2
59     0.998674   0.6
11     0.711224   0.6
161    0.211887   0.2
180    0.697746   0.6
185    0.389306   0.8
193    0.274194   0.2
206    0.519664   0.4
42     0.240168   0.2
212    1.000000   0.6
225    0.291648   0.2
120    0.190455   0.2
144    0.295183   0.2
150    0.243040   0.2
16     0.160407   0.4
198    0.219399   0.2
163    0.237296   0.2
234    0.275298   0.2
240    0.532700   0.2
68     0.379143   0.2
4      0.475475   0.6
21     0.380468   0.2
143    0.529828   1.0
33     0.389306   0.6
63     0.336279   0.6
172    0.092355   0.2
202    0.219399   0.2
231    0.278833   0.4
232    0.188688   0.2
0      0.307556   0.2
69     0.263809   0.2
57     0.515687   0.2
70     0.197746   0.2
158    0.228016   0.2
109    0.248343   0.2
5      0.490941   0.6
106    0.384887   0.2
62     0.175652   0.2
214    0.554574   0.4
152    0.313522   0.4
237    0.657534   0.2
17     0.292090   0.4
88     0.478126   0.2
80     0.361688   0.2
89     0.399691   0.2
160    0.407203   0.6
156    0.996465   1.0
79     0.314185   0.2
134    0.335616   0.2
96     0.534909   0.2
157    0.484534   0.6
201    0.213654   0.2
239    0.573575   0.4
115    0.314627   0.2
131    0.380027   0.2
199    0.230667   0.2
145    0.116659   0.2
217    0.188246   0.2
137    0.244808   0.2
53     0.151790   0.2
108    0.335175   0.2
149    0.098100   0.2
188    0.333186   0.4
65     0.375829   0.4
187    0.605170   0.8
227    0.384004   0.6
48     0.562970   0.4
60     0.380468   0.2
58     0.180513   0.2
83     0.654220   0.2
175    0.659081   0.2
129    0.436368   0.4
113    0.461335   0.2
47     0.648034   0.6
205    0.296067   0.4
116    0.593460   0.6
52     0.701281   0.6
141    0.690013   1.0
139    0.222934   0.2
105    0.271542   0.2
204    0.385771   0.6
23     0.803137   0.6
103    0.427530   0.2
155    0.591692   0.8
7      0.526072   0.6
194    0.298498   0.2
19     0.388422   0.4
147    0.194432   0.2
121    0.228679   0.2
38     0.345117   0.4
81     0.300265   0.2
210    0.596332   0.4
29     0.366328   0.2
162    0.290323   0.4
236    0.210561   0.2
27     0.212550   0.2
111    0.092355   0.0
133    0.203049   0.2
168    0.166151   0.2
8      0.264472   0.2
127    0.252983   0.2
169    0.167035   0.2
34     0.325011   0.2
167    0.632788   0.6
93     0.292753   0.2
216    0.554132   0.8
45     0.336279   0.2
14     0.259832   0.2
146    0.344012   0.4
221    0.228679   0.2
228    0.225586   0.2
223    0.285241   0.4
136    0.160407   0.2
84     0.285241   0.2
235    0.154662   0.2
102    0.910959   0.4
100    0.182943   0.2
192    0.560539   0.2
44     0.603844   0.6
132    0.178966   0.2
117    0.167477   0.2

In [13]:
f_selector.transform(X_train_scaled)

array([[0.63588157, 0.2       ],
       [0.37008396, 0.2       ],
       [0.43305347, 0.2       ],
       [0.29562528, 0.2       ],
       [0.31904551, 0.2       ],
       [0.48917366, 0.2       ],
       [0.42907645, 0.2       ],
       [0.28568272, 0.2       ],
       [0.16062749, 0.4       ],
       [0.62306673, 0.4       ],
       [0.28457799, 0.2       ],
       [0.05921343, 0.2       ],
       [0.28060097, 0.2       ],
       [0.35373398, 0.2       ],
       [0.36986301, 0.2       ],
       [0.16062749, 0.2       ],
       [0.        , 0.        ],
       [0.25872735, 0.2       ],
       [0.21409633, 0.2       ],
       [0.32081308, 0.4       ],
       [0.32589483, 0.2       ],
       [0.46376491, 0.4       ],
       [0.46266019, 0.6       ],
       [0.39637649, 0.2       ],
       [0.1979673 , 0.2       ],
       [0.39438798, 0.2       ],
       [0.99867433, 0.6       ],
       [0.71122404, 0.6       ],
       [0.21188688, 0.2       ],
       [0.69774635, 0.6       ],
       [0.38930623, 0.8       ],
       [0.27419355, 0.2       ],
       [0.51966416, 0.4       ],
       [0.24016792, 0.2       ],
       [1.        , 0.6       ],
       [0.29164825, 0.2       ],
       [0.19045515, 0.2       ],
       [0.29518338, 0.2       ],
       [0.24304021, 0.2       ],
       [0.16040654, 0.4       ],
       [0.21939903, 0.2       ],
       [0.23729563, 0.2       ],
       [0.27529828, 0.2       ],
       [0.53269996, 0.2       ],
       [0.37914273, 0.2       ],
       [0.47547503, 0.6       ],
       [0.3804684 , 0.2       ],
       [0.52982766, 1.        ],
       [0.38930623, 0.6       ],
       [0.33627928, 0.6       ],
       [0.09235528, 0.2       ],
       [0.21939903, 0.2       ],
       [0.27883341, 0.4       ],
       [0.18868758, 0.2       ],
       [0.30755634, 0.2       ],
       [0.2638091 , 0.2       ],
       [0.51568714, 0.2       ],
       [0.19774635, 0.2       ],
       [0.22801591, 0.2       ],
       [0.24834291, 0.2       ],
       [0.49094123, 0.6       ],
       [0.38488732, 0.2       ],
       [0.17565179, 0.2       ],
       [0.55457357, 0.4       ],
       [0.31352187, 0.4       ],
       [0.65753425, 0.2       ],
       [0.29209015, 0.4       ],
       [0.47812638, 0.2       ],
       [0.36168802, 0.2       ],
       [0.39969068, 0.2       ],
       [0.40720283, 0.6       ],
       [0.99646487, 1.        ],
       [0.31418471, 0.2       ],
       [0.33561644, 0.2       ],
       [0.53490941, 0.2       ],
       [0.4845338 , 0.6       ],
       [0.21365444, 0.2       ],
       [0.5735749 , 0.4       ],
       [0.3146266 , 0.2       ],
       [0.38002651, 0.2       ],
       [0.23066726, 0.2       ],
       [0.1166593 , 0.2       ],
       [0.18824569, 0.2       ],
       [0.24480778, 0.2       ],
       [0.15178966, 0.2       ],
       [0.33517455, 0.2       ],
       [0.09809987, 0.2       ],
       [0.33318604, 0.4       ],
       [0.37582855, 0.4       ],
       [0.60517013, 0.8       ],
       [0.38400354, 0.6       ],
       [0.56296951, 0.4       ],
       [0.3804684 , 0.2       ],
       [0.18051259, 0.2       ],
       [0.65422006, 0.2       ],
       [0.65908087, 0.2       ],
       [0.43636765, 0.4       ],
       [0.46133451, 0.2       ],
       [0.64803358, 0.6       ],
       [0.29606717, 0.4       ],
       [0.59346001, 0.6       ],
       [0.70128148, 0.6       ],
       [0.69001326, 1.        ],
       [0.22293416, 0.2       ],
       [0.2715422 , 0.2       ],
       [0.3857711 , 0.6       ],
       [0.80313743, 0.6       ],
       [0.42752983, 0.2       ],
       [0.59169244, 0.8       ],
       [0.52607159, 0.6       ],
       [0.29849757, 0.2       ],
       [0.38842245, 0.4       ],
       [0.19443217, 0.2       ],
       [0.22867875, 0.2       ],
       [0.3451171 , 0.4       ],
       [0.30026513, 0.2       ],
       [0.5963323 , 0.4       ],
       [0.36632788, 0.2       ],
       [0.29032258, 0.4       ],
       [0.2105612 , 0.2       ],
       [0.21254971, 0.2       ],
       [0.09235528, 0.        ],
       [0.20304905, 0.2       ],
       [0.16615113, 0.2       ],
       [0.26447194, 0.2       ],
       [0.25298277, 0.2       ],
       [0.16703491, 0.2       ],
       [0.32501105, 0.2       ],
       [0.63278833, 0.6       ],
       [0.29275298, 0.2       ],
       [0.55413168, 0.8       ],
       [0.33627928, 0.2       ],
       [0.25983208, 0.2       ],
       [0.34401237, 0.4       ],
       [0.22867875, 0.2       ],
       [0.22558551, 0.2       ],
       [0.28524083, 0.4       ],
       [0.16040654, 0.2       ],
       [0.28524083, 0.2       ],
       [0.15466195, 0.2       ],
       [0.9109589 , 0.4       ],
       [0.182943  , 0.2       ],
       [0.56053911, 0.2       ],
       [0.60384445, 0.6       ],
       [0.17896597, 0.2       ],
       [0.1674768 , 0.2       ]])

***Using the Select K best we get total bill and size as the top 2 features for predicitng tip amount.***

### **d. Use recursive feature elimination to select the top 2 features for tip amount. What are they?<br>**

In [14]:
train.head()

     total_bill   tip     sex smoker  day    time  size  price_per_person
173    0.635882  3.18    Male    Yes  Sun  Dinner   0.2          0.961326
24     0.370084  3.18    Male     No  Sat  Dinner   0.2          0.518232
241    0.433053  2.00    Male    Yes  Sat  Dinner   0.2          0.623204
66     0.295625  2.47  Female     No  Sat  Dinner   0.2          0.394107
164    0.319046  3.00  Female    Yes  Sun  Dinner   0.2          0.433149

In [15]:
X_train = train.drop(columns = ['tip'])
X_train.head(3)

     total_bill   sex smoker  day    time  size  price_per_person
173    0.635882  Male    Yes  Sun  Dinner   0.2          0.961326
24     0.370084  Male     No  Sat  Dinner   0.2          0.518232
241    0.433053  Male    Yes  Sat  Dinner   0.2          0.623204

In [49]:
X_train_dum = pd.get_dummies(X_train, columns = ['sex', 'smoker', 'day', 'time'])

X_train_dum.head()

,total_bill,size,price_per_person,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
173,0.635882,0.2,0.961326,1,0,1,0,0,0,0,1,0,1
24,0.370084,0.2,0.518232,1,0,0,1,0,0,1,0,0,1
241,0.433053,0.2,0.623204,1,0,1,0,0,0,1,0,0,1
66,0.295625,0.2,0.394107,0,1,0,1,0,0,1,0,0,1
164,0.319046,0.2,0.433149,0,1,1,0,0,0,0,1,0,1

In [50]:
lm = LinearRegression()

rfe = RFE(lm, n_features_to_select = 2)

In [51]:
rfe.fit(X_train_dum, y_train)

RFE(estimator=LinearRegression(), n_features_to_select=2)

In [52]:
ranks = rfe.ranking_

columns = X_train_dum.columns.tolist()

In [53]:
feature_ranks = pd.DataFrame({'ranking': ranks,
                             'feature': columns})

In [54]:
feature_ranks.sort_values('ranking').reset_index().drop(columns = ('index'))

    ranking           feature
0         1        total_bill
1         1  price_per_person
2         2              size
3         3           day_Fri
4         4         smoker_No
5         5        smoker_Yes
6         6        time_Lunch
7         7          day_Thur
8         8           day_Sat
9         9           day_Sun
10       10       time_Dinner
11       11          sex_Male
12       12        sex_Female

***Using the recursive feature elimination we get total bill and price_per_person as the top 2 features for predicitng tip amount.***

### **e. Why do you think select k best and recursive feature elimination might give different answers for the top features? Does this change as you change the number of features you are selecting?**

***I think it could be from the amount of different features you select to run the tests on. And yes it does change as you change the number of features you are selecting***

## 2. Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

In [31]:
def select_kbest(x,y,k):
    
    f_selector = SelectKBest(f_regression, k = k)
    
    f_selector.fit(x, y)   
    
    f_select_mask = f_selector.get_support()

    f_selector.transform(x)
    
    
    return x.iloc[:,f_select_mask]

In [32]:
select_kbest(X_train_scaled, y_train, 2)

     total_bill  size
173    0.635882   0.2
24     0.370084   0.2
241    0.433053   0.2
66     0.295625   0.2
164    0.319046   0.2
107    0.489174   0.2
91     0.429076   0.2
138    0.285683   0.2
1      0.160627   0.4
39     0.623067   0.4
123    0.284578   0.2
92     0.059213   0.2
22     0.280601   0.2
130    0.353734   0.2
191    0.369863   0.2
196    0.160627   0.2
67     0.000000   0.0
9      0.258727   0.2
209    0.214096   0.2
64     0.320813   0.4
242    0.325895   0.2
35     0.463765   0.4
230    0.462660   0.6
98     0.396376   0.2
97     0.197967   0.2
104    0.394388   0.2
59     0.998674   0.6
11     0.711224   0.6
161    0.211887   0.2
180    0.697746   0.6
185    0.389306   0.8
193    0.274194   0.2
206    0.519664   0.4
42     0.240168   0.2
212    1.000000   0.6
225    0.291648   0.2
120    0.190455   0.2
144    0.295183   0.2
150    0.243040   0.2
16     0.160407   0.4
198    0.219399   0.2
163    0.237296   0.2
234    0.275298   0.2
240    0.532700   0.2
68     0.379143   0.2
4      0.475475   0.6
21     0.380468   0.2
143    0.529828   1.0
33     0.389306   0.6
63     0.336279   0.6
172    0.092355   0.2
202    0.219399   0.2
231    0.278833   0.4
232    0.188688   0.2
0      0.307556   0.2
69     0.263809   0.2
57     0.515687   0.2
70     0.197746   0.2
158    0.228016   0.2
109    0.248343   0.2
5      0.490941   0.6
106    0.384887   0.2
62     0.175652   0.2
214    0.554574   0.4
152    0.313522   0.4
237    0.657534   0.2
17     0.292090   0.4
88     0.478126   0.2
80     0.361688   0.2
89     0.399691   0.2
160    0.407203   0.6
156    0.996465   1.0
79     0.314185   0.2
134    0.335616   0.2
96     0.534909   0.2
157    0.484534   0.6
201    0.213654   0.2
239    0.573575   0.4
115    0.314627   0.2
131    0.380027   0.2
199    0.230667   0.2
145    0.116659   0.2
217    0.188246   0.2
137    0.244808   0.2
53     0.151790   0.2
108    0.335175   0.2
149    0.098100   0.2
188    0.333186   0.4
65     0.375829   0.4
187    0.605170   0.8
227    0.384004   0.6
48     0.562970   0.4
60     0.380468   0.2
58     0.180513   0.2
83     0.654220   0.2
175    0.659081   0.2
129    0.436368   0.4
113    0.461335   0.2
47     0.648034   0.6
205    0.296067   0.4
116    0.593460   0.6
52     0.701281   0.6
141    0.690013   1.0
139    0.222934   0.2
105    0.271542   0.2
204    0.385771   0.6
23     0.803137   0.6
103    0.427530   0.2
155    0.591692   0.8
7      0.526072   0.6
194    0.298498   0.2
19     0.388422   0.4
147    0.194432   0.2
121    0.228679   0.2
38     0.345117   0.4
81     0.300265   0.2
210    0.596332   0.4
29     0.366328   0.2
162    0.290323   0.4
236    0.210561   0.2
27     0.212550   0.2
111    0.092355   0.0
133    0.203049   0.2
168    0.166151   0.2
8      0.264472   0.2
127    0.252983   0.2
169    0.167035   0.2
34     0.325011   0.2
167    0.632788   0.6
93     0.292753   0.2
216    0.554132   0.8
45     0.336279   0.2
14     0.259832   0.2
146    0.344012   0.4
221    0.228679   0.2
228    0.225586   0.2
223    0.285241   0.4
136    0.160407   0.2
84     0.285241   0.2
235    0.154662   0.2
102    0.910959   0.4
100    0.182943   0.2
192    0.560539   0.2
44     0.603844   0.6
132    0.178966   0.2
117    0.167477   0.2

## 3. Write a function named rfe that takes in the predictors, the target, and the number of features to select. It should return the top k features based on the RFE class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

In [63]:
def rfe(x, y, k):
    
    lm = LinearRegression()

    rfe = RFE(lm, n_features_to_select = k)
    
    rfe.fit(x, y)
    
    ranks = rfe.ranking_

    columns = x.columns.tolist()
    
    feature_ranks = pd.DataFrame({'ranking': ranks,
                                 'feature': columns})
    
    return feature_ranks.sort_values('ranking').reset_index().drop(columns = ('index'))

In [64]:
rfe(X_train_dum, y_train, 2)

    ranking           feature
0         1        total_bill
1         1  price_per_person
2         2              size
3         3           day_Fri
4         4         smoker_No
5         5        smoker_Yes
6         6        time_Lunch
7         7          day_Thur
8         8           day_Sat
9         9           day_Sun
10       10       time_Dinner
11       11          sex_Male
12       12        sex_Female

## 4. Load the swiss dataset and use all the other features to predict Fertility. Find the top 3 features using both select k best and recursive feature elimination (use the functions you just built to help you out).

In [55]:
swiss = data('swiss')
swiss.head()

,Fertility,Agriculture,Examination,Education,Catholic,Infant.Mortality
Courtelary,80.2,17.0,15,12,9.96,22.2
Delemont,83.1,45.1,6,9,84.84,22.2
Franches-Mnt,92.5,39.7,5,5,93.40,20.2
Moutier,85.8,36.5,12,7,33.77,20.3
Neuveville,76.9,43.5,17,15,5.16,20.6

In [56]:
swiss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, Courtelary to Rive Gauche
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fertility         47 non-null     float64
 1   Agriculture       47 non-null     float64
 2   Examination       47 non-null     int64
 3   Education         47 non-null     int64
 4   Catholic          47 non-null     float64
 5   Infant.Mortality  47 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 2.6+ KB

In [57]:
train, val_test = train_test_split(swiss, train_size=0.6, random_state=22)
    
val, test = train_test_split(val_test, train_size=0.5, random_state=22)

train.shape, val.shape, test.shape

((28, 6), (9, 6), (10, 6))

In [58]:
mms = MinMaxScaler()

train[['Agriculture', 'Examination', 'Education', 'Catholic', 'Infant.Mortality']] = mms.fit_transform(train[['Agriculture', 'Examination', 'Education', 'Catholic', 'Infant.Mortality']])

train.head()

,Fertility,Agriculture,Examination,Education,Catholic,Infant.Mortality
Glane,92.4,0.752542,0.323529,0.134615,0.970976,0.892405
Paysd'enhaut,72.0,0.703955,0.088235,0.038462,0.004190,0.455696
Nyone,56.6,0.561582,0.558824,0.211538,0.132754,0.373418
Lavaux,65.1,0.811299,0.470588,0.153846,0.007052,0.582278
Broye,83.8,0.779661,0.382353,0.115385,0.926929,0.810127

In [40]:
X_train_scaled_swiss = train[['Agriculture', 'Examination', 'Education', 'Catholic', 'Infant.Mortality']]
y_train_swiss = train['Fertility']

In [59]:
select_kbest(X_train_scaled_swiss, y_train_swiss, 3)

              Examination  Education  Catholic
Glane            0.323529   0.134615  0.970976
Paysd'enhaut     0.088235   0.038462  0.004190
Nyone            0.558824   0.211538  0.132754
Lavaux           0.470588   0.153846  0.007052
Broye            0.382353   0.115385  0.926929
Lausanne         0.676471   0.519231  0.101788
Val de Ruz       0.352941   0.115385  0.028820
Franches-Mnt     0.058824   0.076923  0.932550
Neuchatel        0.941176   0.596154  0.150945
Rolle            0.382353   0.173077  0.056924
Echallens        0.441176   0.019231  0.225345
Porrentruy       0.176471   0.115385  0.903628
Herens           0.058824   0.019231  1.000000
Le Locle         0.558824   0.230769  0.092693
Sion             0.294118   0.230769  0.967603
Oron             0.264706   0.000000  0.002555
Cossonay         0.558824   0.076923  0.006847
La Vallee        0.823529   0.365385  0.000000
Yverdon          0.352941   0.134615  0.040368
ValdeTravers     0.647059   0.115385  0.066428
Entremont        0.117647   0.096154  0.996730
Gruyere          0.264706   0.115385  0.976188
Morges           0.558824   0.173077  0.031477
Boudry           0.676471   0.211538  0.035462
Sierre           0.000000   0.038462  0.994481
Courtelary       0.352941   0.211538  0.079816
V. De Geneve     1.000000   1.000000  0.410731
Neuveville       0.411765   0.269231  0.030761

In [65]:
rfe(X_train_scaled_swiss, y_train_swiss, 3)

   ranking           feature
0        1       Examination
1        1         Education
2        1  Infant.Mortality
3        2       Agriculture
4        3          Catholic